github: whoisarepo # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: whoisarepo # Replace with a single Patreon username
open_collective: whoisarepo # Replace with a single Open Collective username
ko_fi: whoisarepo # Replace with a single Ko-fi username
tidelift: whoisarepo # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: whoisarepo # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: whoisarepo # Replace with a single Liberapay username
