[configuration]
plugins = ["header", "activities", "footer"]
version = "0.0.1"
basePath = "docs"
extension = ".md"
output = "README.md"

[[section]]
name = "HEADER"


[[section]]
id = "activities"
path = "ACTIVITIES"

[[section]]
id = "footer"
path = "FOOTER"
