/**
 * Base Template
 * Provides generation metadata and version stamping for README output
 * 
 * @module templates/base
 */

import { createHash } from "crypto";
import { defineTemplate } from "@/utils";



// =============================================================================
// Version & Build Information
// =============================================================================

/**
 * Generate a unique version hash based on timestamp and random seed
 */
export const generateVersionHash = (): string => {
    const timestamp = Date.now().toString();
    const seed = Math.random().toString(36).substring(2, 8);
    const data = `arepodesir-${timestamp}-${seed}`;
    return createHash("sha256").update(data).digest("hex").substring(0, 12);
};

/**
 * Build metadata for README generation
 */
export interface BuildMetadata {
    readonly versionHash: string;
    readonly timestamp: Date;
    readonly generator: string;
    readonly version: string;
    readonly mach: string;
}

/**
 * Create build metadata
 */
export const createBuildMetadata = (): BuildMetadata => ({
    versionHash: generateVersionHash(),
    timestamp: new Date(),
    generator: "arepodesir",
    version: "1.001",
    mach: "1.0001",
});

// =============================================================================
// Base Template
// =============================================================================

/**
 * Generate the hidden comment header with version hash and metadata
 * This is a function that creates fresh metadata on each call
 */
export const renderBaseComment = (): { comment: string; metadata: BuildMetadata } => {
    const meta = createBuildMetadata();
    const isoDate = meta.timestamp.toISOString();

    const comment = [
        `<!--`,
        `  ╭─────────────────────────────────────────────────────────────────────────╮`,
        `  │  ✨ FABULOUSLY GENERATED BY AREPODESIR ✨                               │`,
        `  │  💖 Made with love, sparkles & fabulous vibes 💖                       │`,
        `  ├─────────────────────────────────────────────────────────────────────────┤`,
        `  │  🏷️  Version Hash: ${meta.versionHash.padEnd(50)} │`,
        `  │  📅 Generated: ${isoDate.padEnd(53)} │`,
        `  │  🔧 Generator: ${meta.generator.padEnd(53)} │`,
        `  │  📦 Version: ${meta.version.padEnd(55)} │`,
        `  │  ⚡ MACH: ${meta.mach.padEnd(59)} │`,
        `  ╰─────────────────────────────────────────────────────────────────────────╯`,
        `  `,
        `  This README was sexily crafted by the arepodesir generator.`,
        `  Serving README realness since 2024 💅`,
        `  For more info: https://github.com/arepodesir/arepodesir`,
        `-->`,
    ].join("\n");

    return { comment, metadata: meta };
};