[metadata]
version = "0.0.1"


[globals]
basePath = "docs"
extension = ".md"
output = "README.md"

[[section]]
id = "header"
path = "HEADER"

[[section]]
id = "social-media"
path = "SOCIAL MEDIA"

[[section]]
id = "header"
path = "HEADER"

[[section]]
id = "header"
path = "HEADER"
