[metadata]
version = "0.0.1"
basePath = "docs"
extension = ".md"
output = "README.md"

[[section]]
id = "header"
path = "HEADER"

[[section]]
id = "activities"
path = "ACTIVITIES"

[[section]]
id = "footer"
path = "FOOTER"
